# searchresult_views.py

# The searchresult_views.py file defines a basic ViewSet for the SearchResult model
# This is a Django REST Framework ViewSet that provides full CRUD operations (list, retrieve, create, update, delete) for the SearchResult model
# SearchResult represents individual search result entries generated by a manual or scheduled Amazon

from rest_framework import viewsets

from base.models import SearchResult
from base.serializers import SearchResultSerializer


class SearchResultViewSet(viewsets.ModelViewSet):
    queryset = SearchResult.objects.all()
    serializer_class = SearchResultSerializer
