# Generated by Django 5.1 on 2025-04-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_pricehistory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
