# Generated by Django 5.1 on 2025-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_trackedproduct_target_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
