# Generated by Django 5.1 on 2025-05-18 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pricehistory_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='scheduled_scraping_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='scraping_time',
            field=models.TimeField(default=datetime.time(3, 0)),
        ),
    ]
