# Generated by Django 5.1 on 2025-05-18 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_trackedproduct_scheduled_scraping_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedproduct',
            name='scheduled_scraping_enabled',
        ),
        migrations.RemoveField(
            model_name='trackedproduct',
            name='scraping_time',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='scheduled_scraping_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='scraping_time',
            field=models.TimeField(default=datetime.time(3, 0)),
        ),
    ]
